### ISSUE TITLE
Documentation query, hows authentication handled between frontend and backend?

### ISSUE THREAD

**Issue by anoopemacs** [tmiller02/cookiecutter-django-react-ansible#2]
How is authentication and authorisation between React frontend and Django API handled:-

1) JWT tokens?
Or 
2) Django SessionAuthentication?

**Comment by tmiller02** [comment]
Hi, At the moment this cookiecutter template does not provide any user authentication between react and django.

If you're thinking of adding user authentication, I'd suggest using JWT tokens with https://github.com/davesque/django-rest-framework-simplejwt

**Comment by anoopemacs** [comment]
Thank you for the suggestion to go with JWT tokens route.
